### ISSUE TITLE
Specification and Schema for the main logical input objects

### ISSUE THREAD

**Issue by Perseverance** [eea-oasis/baseline#120]
Create a specification and Schema for the main logical input objects based on the baseline-administrator library. Also add specification for how the resolvers of these look like.

More info coming.

**Comment by ognjenkurtic** [comment]
@Perseverance is this issue still relevant? I ll close due to inactivity if no reply until next Thusday.

**Comment by Therecanbeonlyone1969** [comment]
Closing as addressed in spec
