### ISSUE TITLE
Generalize the Shield contract transaction types

### ISSUE THREAD

**Issue by Perseverance** [eea-oasis/baseline#128]
The current Shield contract, part of the Radish34 setup has TransactionTypes tailored to the Radish use case. In order to make this contract more reusable in other use-cases the transaction types can be dynamically created.

Idea how this can be implemented:
Remove the transactionTypes enum and add a method allowing the administrator to add new transaction types (index, name). Change radish34 deployment procedure and tests to account for calling this method to set up the transaction types.
Allow for inspection of transaction type name by index.

**Comment by skarred14** [comment]
Good issue! Shield i think could fit into the overall "upgradable" pattern

**Comment by davemec** [comment]
I am starting to look into this story, please let me know if there is any conflict.

**Comment by ognjenkurtic** [comment]
@Kasshern @skosito @Ybittan @biscuitdey This discussion might be relevant for our work on the SRI. Keeping it open so that we can discuss.
