### ISSUE TITLE
Benchmark Zokrates programs

### ISSUE THREAD

**Issue by hadasz** [eea-oasis/baseline#139]
## Overview

Using [zkp-benchmarker](https://github.com/ConsensysHealth/zkp-benchmarker), benchmark Zokrates programs used in Radish-34. 

### Reference

[zkp-benchmarker](https://github.com/ConsensysHealth/zkp-benchmarker)

### Acceptance

This will be completed when benchmarks on runtime and memory usage of compile, setup, and generate-proof have been gathered and aggregated over several iterations for the Zokrates programs included in Radish-34

## Tasks

- Go to  [zkp-benchmarker](https://github.com/ConsensysHealth/zkp-benchmarker)
- Pull the code, build
- Put relevant Zokrates programs in the circuits directory according to the README
- Edit YAML file according to README
- Run the zkp-benchmarker command line for 10 iterations
- Gather data from resulting csv files

**Comment by hadasz** [comment]
I don't have permissions to assign this to myself, but I intend to work on this issue

**Comment by humbitious** [comment]
How is this going? When would you like to set a review point with SSC?

**Comment by hadasz** [comment]
Still a work in progress. Will update when ready to review with SSC.

**Comment by gleim** [comment]
Work completed.  Paper to be submitted to conference this week.  Informal update will be provided to Baseline community soon.
