### ISSUE TITLE
Add Zokrates overflow  (modulus p) to Cross-DSL language

### ISSUE THREAD

**Issue by hadasz** [eea-oasis/baseline#158]
In order to implement EdDSA in the Cross-DSL language, I need to add the following feature: If you use a number above p , the number is read as num%p.

**Comment by humbitious** [comment]
Hey Hadasz, if you think this will get worked in the next two weeks before next TSC, we can pull this to In-Progress. If not, we can pull to Backlog until it goes live.

**Comment by gleim** [comment]
Closed as Deprecated
