### ISSUE TITLE
Current Baseline Smart Contract system is not upgradeable

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/baseline#222]
## Overview

The current Baseline smart contract system cannot be upgraded in case a relevant security vulnerability is discovered or new features are introduced that support such things as scalability, new security features, new baseline functionality, new zk-snarks or other zkp technology.

### Reference

- https://docs.openzeppelin.com/upgrades-plugins/1.x/

### Questions

- Is upgradability a desired business feature?

### Assumptions

- Ethereum as the underlying DLT

### Acceptance

- Build and test upgradeable Baseline contracts

## Tasks

- PR with unit tests that make current or improved Baseline contracts upgradeable

**Comment by ognjenkurtic** [comment]
@Kasshern @skosito @Ybittan @biscuitdey This discussion might be relevant for our work on the SRI. Keeping it open so that we can discuss.
