### ISSUE TITLE
Address extensibility of queueing system for baseline

### ISSUE THREAD

**Issue by skarred14** [eea-oasis/baseline#24]
## Overview

As a developer (admin/general) user, I would like to abstract components of interaction across the different microservices in a modular manner. To this extent, leverage the queuing system to establish a reusable process for managing workers and job queues for complex system to system interaction. Currently, the only process that deals with the queues, is the interaction of `api` with `messenger` on radish34. The purpose of this feature request is to abstract interactions to a modular workflow, where in each step in a workflow can be represented in terms of API -> Messenger; API -> ZKP -> Blockchain -> Messnger; etc. 

Here is a general suggested outlay of workflow steps:
Workgroup = set of orgs defined in the orgRegistry set up as a group of participants in a business relationship
Workflow = the series of things a set of counterparties agreed upon as a process flow. For example, in the case of Radish34, it is RFP -> MSA -> PO.
Step = A single baselined Record/Function/BusinessEvent/Document (e.g,. RFP, MSA, PO) process in a workflow
Tasks = A series of jobs which can be a composition of multiple interactions or system actions that constitute a step or span across multiple tests. Example in the case of an MSA step is: select a set of counterparties, serializing a record, sending messages, executing off-chain functions (not in Radish34, but definitely in protocol-compliant stack), executing and sending/receiving EdDSA sigs, invoking ZK service, ensuring  that the ZK circuit (or a code package/container in a non-Radish34 implementation) of a previous Step is executed correctly, etc.

Note that some of this work has been begun on a development branch on this repo 
### Reference

- [MSA Process Abstraction](https://app.gitbook.com/@baseline/s/baseline-protocol/radish34/radish34-diagrams)
- [Baseline Queue](https://github.com/ethereum-oasis/baseline/tree/development)

### Acceptance

- Successfully run integration tests on radish34 master

## Tasks

- [ ] Complete MSA process in radish34 as an extension of a baseline workflow mechanism
- [ ] Comple PO process in radish34

**Disclaimer: This is a broad stroke and a sample feature request. It would need to be further updated (potentially broken down into further feature requests), based on discussions with other members of the Oasis community

**Comment by kthomas** [comment]
I have done a good bit of work recently that I believe could be highly relevant here. Will take a look at your branch that has the WIP for this and we can discuss 👍

**Comment by skarred14** [comment]
Thats great! looping in @pmacom the author of the said branch

**Comment by skarred14** [comment]
@kthomas @bitwiseguy can we close or wrap this issue? It looks like the new PR https://github.com/ethereum-oasis/baseline/pull/227, should address the queueing bases using NATS.

**Comment by ognjenkurtic** [comment]
@Kasshern @skosito @Ybittan @biscuitdey This discussion might be relevant for our work on the SRI. Keeping it open so that we can discuss.
