### ISSUE TITLE
Prepare a proposal for the BPI Subject and Accounts handling component as part of the SRI

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#476]
## Overview

We need to prepare a document outlining basic functionalities and interfaces before starting the implementation of the SRI.
 
### Acceptance

- Document created and presented to the team
- Team agrees on the interfaces and set of functionalities that can be implemented in the first run.

## Tasks

- [ ] Document created
- [ ] Document presented to the team
- [ ] Decision made about the interfaces
- [ ] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
Work done so far can be tracked [here](https://drive.google.com/file/d/1D863zv2SlmtjZLrUsUplDRUcrUaUX9gE/view?usp=sharing)

We added standard excerpts that in our eyes describe the minimum requirements that the component needs to fulfill in order to  be able to provide a meaningful   functionality as part of a SRI example use-case.

We plan another meeting to define a interface proposal, before we meet on Thursday to present it.

**Comment by Therecanbeonlyone1969** [comment]
@ognjenkurtic @skosito please, reference the [API spec](https://github.com/eea-oasis/baseline-standard/blob/main/api/baseline-api-v1.0-psd01.md) when designing internal interfaces -- external one are defined in the document. The schemas will allow you to design the internal models for relevant tables etc. Happy to discuss but 6 am my time was too early for me on a holiday.

**Comment by skosito** [comment]
@Therecanbeonlyone1969 thanks for the hint!
sorry for the session time, we already scheduled it beforehand and I think it was just misunderstanding - however @ognjenkurtic and me will have one more this week plus the regular weekly sync with whole SRI team so there will be opportunities to discuss this soon 👍 
we will reach out to you to try and find better time for follow up discussion

**Comment by ognjenkurtic** [comment]
@Therecanbeonlyone1969 we have a first proposal of the API ready, with 6 or 7 questions. [Here](https://docs.google.com/document/d/1DCi0Ap9EK2cBxxEVzmOPkdkcl1hnv7-qoELGHODb1PM/edit?usp=sharing). Please have a look when you find time. We are starting with implementation and will implement changes based on the answers as we go.

**Comment by Therecanbeonlyone1969** [comment]
@ognjenkurtic left answers and comments in the doc. Apologies for the delay. I will be more responsive going forward

**Comment by ognjenkurtic** [comment]
@Therecanbeonlyone1969 thanks. We went thought and applied them and left additional two questions. Please have a look when you have time. We ll work on the implementation of the  clarified items in parallel.
