### ISSUE TITLE
Introduce a linter and formatting style for the SRI project

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#492]
## Overview

We need this to make sure formatting is uniform across the project.

### Reference

- [Follows from this issue](https://github.com/eea-oasis/baseline/issues/491)

### Questions

- Linter?
- Style?

### Acceptance

- Linter introduced
- Formatting style agreed and introduces

## Tasks

- [ ] Linter setup and running locally

**Comment by Kasshern** [comment]
I vote for typescript-eslint and a modified version of prettier.

**Comment by Manik-Jain** [comment]
> I vote for typescript-eslint and a modified version of prettier.

+1 for typescript-eslint. I think default prettier does pretty good job, is there a reason for the proposed modification?

**Comment by skosito** [comment]
Its probably best to go with default options and no (or very minial) config in both linter and prettier for start

**Comment by Kasshern** [comment]
You make a very good point @skosito. You have convinced me, albeit reluctantly, to adopt default options for both the linter and prettier.
