### ISSUE TITLE
SRI folder structure

### ISSUE THREAD

**Issue by Manik-Jain** [eea-oasis/baseline#510]
## Overview

Reorganize current SRI folder structure and basic initial setup:

1. Segregate the model classes/interfaces in a dedicated folder that can be shared across NestJS modules
2. Have a base interface with fields like id, name, description that can be inherited for types having these common fields 
3. instead of having a mix of interfaces and class declarations,  define a common structure across SRI

## Tasks

- [ ] A list of tasks that need
- [ ] to be done to call this issue done

**Comment by ognjenkurtic** [comment]
Please vote on the point 1. 
Point number 2 should be postponed for later phase of the project.
Point 3 tackled in a separate issue.

**Comment by ognjenkurtic** [comment]
Regarding point 1, i would vote we keep the structure as is (domain objects placed inside of the models folder for each component). 

My argumentation is that domain objects contain business logic (they are not storage models) so they should be placed inside of their relevant component and close to command handlers that rely on them. 

Storage models on the other side could be placed in a shared\common folder as they are dumb and are only used for a single purpose - storage.

Also, refactoring domain objects to a shared folder later in the project is trivial, so  we can easily do that if we see that this structure is causing problems.

**Comment by Kasshern** [comment]
I vote for keeping domain objects inside models folder within components. If the only up side to isolating them in a separate folder is organization, that refactor can be done when necessary. Unless @Manik-Jain can provide good reason otherwise.

**Comment by Manik-Jain** [comment]
Yeah the initial idea was to organize the model classes inside a common models folders, that can then be shared across different NestJS components. But I do agree that this is not a blocker at the moment, and can be deferred to future work, if needed. 

We can have a Model-Controller-Service code style inside each component/sub-component.

**Comment by Therecanbeonlyone1969** [comment]
Agree with @ognjenkurtic @Kasshern ... simplicity 1st

**Comment by ognjenkurtic** [comment]
@Manik-Jain please close the issue if this is resolved for now. We ll open another one down the road if the need arises.
