### ISSUE TITLE
Write generic mappers for BRI-3 (SRI)

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#517]
## Overview

Check following TODOs:
- Write generic mapper domainObject -> DTO
- Write generic mapper prismaModel -> domainObject
- Write generic mapper domainObject -> prismaModel

### Reference

TODOs introduced in this PR https://github.com/eea-oasis/baseline/pull/515

**Comment by ognjenkurtic** [comment]
Added additional TODO comments related to mapping to the description of the issue.
