### ISSUE TITLE
Introduce validation for incoming DTOs for BRI-3

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#520]
## Overview

We need validation of the input DTOs to intercept invalid inputs even reaching the level of command handlers.

### Reference

https://docs.nestjs.com/techniques/validation

### Questions

Can this validation be tested using unit tests or do we need to test with e2e?

### Acceptance

- Each input DTO is validated and the request rejected with BadRequest in case validation fails
-  
## Tasks

- [x]  Implement validation pipe (middleware) for all existing input DTOs
- [x]  Implement tests for the validation via unit or e2e tests

**Comment by Therecanbeonlyone1969** [comment]
I really like the validationPipe and validator options in the class.

**Comment by ognjenkurtic** [comment]
Just tried it out on a branch. Unit tests of the controller are not triggering this validation, so we should write a test file for each DTO and do something like this:

it('should throw when the planned quantity is a negative number.', async () => {
  const importInfo = { productCode: 4567, plannedQuanity: -10 }
  const ofImportDto = plainToInstance(OfImportDto, importInfo)
  const errors = await validate(ofImportDto)
  expect(errors.length).not.toBe(0)
  expect(stringified(errors)).toContain(`Planned Quantity must be a positive number.`)
}

[source](https://stackoverflow.com/questions/60852170/nestjs-how-to-unit-test-a-dto)

Will try out tomorrow.
