### ISSUE TITLE
BPISubject `publicKey` as an object for BRI-3

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/baseline#523]
## Overview

`publicKey` used in the BPISubject should be a key-value object (as a map) to allow for more than one public key to be associated with a BPISubject e.g.

```
[publicKey, {keyAlg, keyType}]
```

### Reference

- Issue #488 

### Assumptions

-More than 1 pubkey per BPISubject

**Comment by Manik-Jain** [comment]
Hi @Therecanbeonlyone1969 

Could you please provide some details on the KV {keyAlg, keyType}.
What are the possible values that we can hold in these keys?

**Comment by Therecanbeonlyone1969** [comment]
> Hi @Therecanbeonlyone1969
> 
> Could you please provide some details on the KV {keyAlg, keyType}. What are the possible values that we can hold in these keys?

Sure. each `publicKey` must minimally be associated with a `keyRepresentation` e.g. `JWK` (JSON Web Key), `base64` and `keyAlg` e.g. `secp256k1` or `ed25519` @Manik-Jain

**Comment by ognjenkurtic** [comment]
2023-01-26 SRI-3 call - Decision is to wait with implementation until we finish the milestone 3 at least. We just assume the PK stored currently is of a single type. We ll revisit as soon as milestone 3 is done.
