### ISSUE TITLE
Add reference to proUBC to BRI-1 examples

### ISSUE THREAD

**Issue by fleischr** [eea-oasis/baseline#530]
## Overview

Adding a reference to summarize proUBC as an example of BRI-1 with additional links on how to clone and use proUBC

### Reference

Refers to https://github.com/provideplatform/proUBC

### Questions

No additional questions

### Assumptions

Other BRI-1 components may reorganized under https://github.com/prvd-oasis or elsewhere, but reference documents such as this one will remain in BRI-1 folder

### Acceptance

Add the PROUBC-intro.md

## Tasks

Add the PROUBC-intro.md

**Comment by fleischr** [comment]
I am still planning to open a new PR to complete this using some of the feedback previously offered. Shall I create a new issue then? @Ybittan

**Comment by Ybittan** [comment]
> I am still planning to open a new PR to complete this using some of the feedback previously offered. Shall I create a new issue then? @Ybittan 

Ah I see, I closed the issue because I noticed there was a merged PR linked to it. But if there's more to be done relevant to what's already mentioned here we can reopen this one no problem.

**Comment by fleischr** [comment]
closing this issue - two reasons.
1. proUBC has been renamed to provide-abap.
2. Any references to provide-abap will be context specific - such as with the BPI interop use case. provide-abap's core source code will be external in own open source repo - but some scripts on how it can be leveraged may be introduced to baseline periodically.
