### ISSUE TITLE
change response DTO interfaces to classes

### ISSUE THREAD

**Issue by Manik-Jain** [eea-oasis/baseline#558]
## Overview

Currently we have been using interfaces for response DTOs. In order to have validation and auto-mapper capabilities, we have agreed to change interfaces to classes to make use of auto-mapping. 

### Reference

https://automapperts.netlify.app/docs/nestjs

### Acceptance

 all DTOs are changed to classes

## Tasks

- [ ] A list of tasks that need
- [ ] to be done to call this issue done

**Comment by ognjenkurtic** [comment]
Hi @Manik-Jain this change is minor as explained here. Guess you can bundle it with the nestjs automapper implementation and do everything under this issue?

**Comment by Manik-Jain** [comment]
PR https://github.com/eea-oasis/baseline/pull/565 raised for this change

**Comment by Manik-Jain** [comment]
PR https://github.com/eea-oasis/baseline/pull/565 merged
