### ISSUE TITLE
[SRI] Add missing fields to Bpi Subject Account

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#563]
## Overview

Check https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#r80 and add missing fields. Can be done as placeholder if we dont have proper models to use.

### Reference

Comment from PR where this was brought up https://github.com/eea-oasis/baseline/pull/546#discussion_r998784868

### Questions

- None

### Assumptions

- None

### Acceptance

- All needed fields are added in all layers in application

## Tasks

- [x] Add missing fields to all layers (models, dto, api etc)
- [x] Unit tests modifications

**Comment by Ybittan** [comment]
[PR 615](https://github.com/eea-oasis/baseline/pull/615) completes these tasks
