### ISSUE TITLE
[SRI] Prepare proposal on authn

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#569]
## Overview

We need to prepare a document outlining basic authn and authz functionalities.
 
### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [ ] Document created
- [ ] Document presented to the team
- [ ] Decision made about the interfaces
- [ ] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
Working proposal created by @Manik-Jain is [here](https://docs.google.com/document/d/1A4wr7Vqt9mUoDezKI5njk6eKRixGP1nUgxUe_E7pay0/edit?usp=sharing)
