### ISSUE TITLE
[SRI] Prepare proposal on authz

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#570]
## Overview

We need to prepare a document outlining basic authz functionalities. This includes security policies.
Doc https://docs.google.com/document/d/1Gl1jxRTdGMOBSqb7bexC2znHIhd2a7WzJBMsT_rvDi4/edit
 
### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [x] Document created
- [x] Document presented to the team
- [x] Decision made about the interfaces
- [x] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
Added my comments to the doc. Let me know if you need help with defining the interfaces in the doc and\or creating issues it
