### ISSUE TITLE
[SRI] Prepare proposal on messaging

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#571]
## Overview

We need to prepare a document outlining basic messaging functionalities. Check this one too https://github.com/eea-oasis/baseline/issues/514 to expand current document linked there
 
### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [x] Document created
- [x] Document presented to the team
- [x] Decision made about the interfaces
- [x] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
Work in progress document: https://docs.google.com/document/d/1ZjHCKqhkG7SeaBTECyR6HyphHhbIGTcbOLahnEW004o/edit
