### ISSUE TITLE
[SRI] Prepare proposal on workgroup invitations

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#572]
## Overview

We need to prepare a document outlining basic invitation functionalities.

Doc: https://docs.google.com/document/d/16rGQfOrA09piDp9B6Qd-YZH4s5G6ncpn5AV0TU31MjQ/edit
### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [] Document created
- [] Document presented to the team
- [] Decision made about the interfaces
- [] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
This one is waiting on #571 to be defined.

**Comment by skosito** [comment]
@ognjenkurtic can we close this one?
