### ISSUE TITLE
[SRI] Prepare proposal on privacy policy

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#573]
## Overview

We need to prepare a document outlining privacy policies.
 
### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [] Document created
- [] Document presented to the team
- [] Decision made about the interfaces
- [] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
This one will be tackled after the security policies approach is defined here #570
