### ISSUE TITLE
[SRI] Prepare proposal on workgroup set up

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#574]
## Overview

We need to prepare a document outlining basic workgroup set up functionalities.
[Workgroup Setup Proposal](https://docs.google.com/document/d/1pV9yOIRKfj9uBobKh1s2KZI44gfmWOEDr1_wTqtxPZk/edit?usp=sharing
 )
### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [x] Document created
- [x] Document presented to the team
- [x] Decision made about the interfaces
- [x] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
@Kasshern What is the status of this one now that you have the first implementation issue opened? Do we want to add a simple interface definition to the Wokgroup Setup Proposal doc and close this one?

**Comment by Kasshern** [comment]
Changes made
