### ISSUE TITLE
[SRI] Prepare proposal to record history of state changes

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#587]
## Overview

We need to prepare a document outlining the flow and components required to capture the history of state changes of a document.
 
### Reference

- [State Change Flow](https://docs.google.com/document/d/1XddSwbX4BNhIDnbXu2GFuDO5mgmgwXbqO_QFvrqe5hM/edit?usp=sharing)

### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [x] Document created
- [x] Document presented to the team
- [x] Decision made about the interfaces
- [x] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
Document is ready for review before we start doing issues out of it.

**Comment by biscuitdey** [comment]
The document is completed and reviewed.

**Comment by biscuitdey** [comment]
The document is completed and reviewed.
