### ISSUE TITLE
[SRI] authentication unit test case changes

### ISSUE THREAD

**Issue by Manik-Jain** [eea-oasis/baseline#591]
## Overview

Since all endpoints are going to be allowed only to the authenticated users, all the existing unit tests need to have a valid jwt token passed in each request.

**Comment by ognjenkurtic** [comment]
I am not sure 100% but i think existing unit tests will not be aware of the JWT auth if the auth is implemented as a NestJS middleware. Middlewares are not triggered when running a controller through the testing module. Please recheck. We ll need separate unit tests for the auth stuff and we ll test it through e2e tests later.
