### ISSUE TITLE
[SRI] Find a way to mock Prisma in way that allows us to ditch writing mock storage agents in unit tests

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#632]
## Overview

This way we can mock the DB so that everything else is tested and we avoid writing bolierplate code.

### Reference

- [Prisma Client mock Github issue](https://github.com/prisma/prisma1/issues/3898)

### Questions

n/a

### Assumptions

- Nobody wants to write mock storage agents

### Acceptance

- Mock of prisma client implemented with a nice way to provide seed data
- All mock storage agents ditched
- All unit tests still pass

## Tasks

- [ ] Implenent it

**Comment by Ybittan** [comment]
https://www.prisma.io/docs/guides/testing/unit-testing
