### ISSUE TITLE
Proposal Document on State Object CRUD

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline#637]
## Overview

Create a proposal for the state object CRUD module within BRI-3 

### Reference

- [State Object CRUD Proposal Document](https://docs.google.com/document/d/1sitzsboY3oUzjG5SoweLDvTiiQ4A-yLUEOTqdu1U8q8/edit?usp=sharing)
- [Implementation Issue](https://github.com/eea-oasis/baseline/issues/629)

### Questions

- What should the state object contain and what from should it take?

### Acceptance

- Document created and presented to the team
- Team agrees on set of functionalities that can be implemented in the first run.

## Tasks

- [x] Document created
- [x] Document presented to the team
- [x] Decision made about the interfaces
- [x] Created GitHub issues for stories for implementation

**Comment by ognjenkurtic** [comment]
State proposal document is located [here](https://docs.google.com/document/d/1sitzsboY3oUzjG5SoweLDvTiiQ4A-yLUEOTqdu1U8q8/edit). It is referenced in the SRI use-case document [here](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit) and will be implemented as part of [this](https://github.com/eea-oasis/baseline/issues/702) and subsequent issues.
