### ISSUE TITLE
[SRI] Add caller location to log statements

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#638]
## Overview

Call to log something currently produces this output:
![image](https://user-images.githubusercontent.com/23699661/217271336-5fe68ef9-65b9-4139-bb5d-3cdd2f26e4e6.png)

Check if it is possible to instead print out the location from which the logging was invoked for that particular statement, and implement the change.

### Reference

- n/a

### Questions

- n/a

### Assumptions

- n/a
- 
### Acceptance

- List of what needs to be true
- to consider this done
- done done

## Tasks

- [ ] Check and implement if possible

**Comment by Therecanbeonlyone1969** [comment]
> This is Siyuan Fan. Could you assign this issue to me?

done
