### ISSUE TITLE
Using Rinkeby testnet

### ISSUE THREAD

**Issue by fosgate29** [eea-oasis/baseline#661]
https://github.com/eea-oasis/baseline/blob/92ac6dc4d146267ea79235870f41badda927a28d/examples/financialcircuit/README.md?plain=1#L91

It has reference to a smart contract deployed on Rinkeby testnet that was deprecated.

A new smart contract should be deployed on a new testnet.

**Comment by skosito** [comment]
Why not goerli? Do we need more changes, like rpc url changes etc?

**Comment by fosgate29** [comment]
1) It could be Goerli. The problem was I had much more Matic than Goerli ether.  
2) No more changes since it was a static/manual test. It was just to demonstrate a curious user how a Verifier smart contract would work.
