### ISSUE TITLE
[SRI] Can't log in due to case-sensitivity

### ISSUE THREAD

**Issue by mkxx712** [eea-oasis/baseline#671]
## Expected Behavior
Return an access token after successfully logging in.

## Actual Behavior
Return an error "Signature xxx for public key xxx is invalid."
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/122747873/234095048-bd7082a1-defb-4266-9e1e-81ce50d35b4a.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/122747873/234095461-1fbf598a-4881-47fe-b73f-0d7145ce179d.png">

![image](https://user-images.githubusercontent.com/122747873/234094389-ce3c4a5e-e367-48d7-a349-4c780ca6cb94.png)

## Steps to Reproduce the Problem

  1. Use an address that includes both upper and lower cases.
  2. Try to log in

**Comment by skosito** [comment]
closing since PR is merged
