### ISSUE TITLE
[SRI] Two TODOs in Login.js

### ISSUE THREAD

**Issue by mkxx712** [eea-oasis/baseline#672]
## Overview
The Login.js is in bri-3/front-end/src/login folder.
The two TODOs are:
    - add toast library and show success/failure login with error messages
    - add logged in user details on UI
After this issue, the user will be able to see his/her public key & access token directly on UI, and will receive a success toast.

### Reference

- Toast library: [React-Toastify](https://fkhadra.github.io/react-toastify/introduction)

### Questions

- About UI: Is there any other requirements in addition to the two original TODOs' contents? (e.g. What user details? What type of UI is more preferred? What kind of goal is the UI want to achieve?)
- About Influence: Currently I'll only change index.js, without creating any new file, which will cause minimal/no influence on other parts of the project. Is that OK?

### Assumptions

n/a

### Acceptance

n/a

## Tasks

- [x] add toast library and show success/failure login with error messages
- [x] add logged in user details on UI

**Comment by skosito** [comment]
closing since PR is merged
