### ISSUE TITLE
Document DID auth in more details 

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#677]
## Overview

It needs a little bit more details about how it works in order to be easier to grasp by someone not familiar with DIDs. Adding a few sentences around the variables and an explanation of the authentication flow should suffice.

### Reference

- n/a

### Questions

- n/a

### Assumptions

- n/a

### Acceptance

- DID auth explained in more details

## Tasks

- [ ] Update readme and .env.sample

**Comment by fleischr** [comment]
Glad to see this topic looked at! Its one that's really bigger than Baseline itself imo. I have my own thoughts to share here.

DIDs by themselves have multiple authentication means by which they are generated depending on the issuer and user. I think this where people may get most confused - the DID can be created either with a seed phrase/private key and/or a composition of other data/credentials. 

Relative to baseline, DIDs are used to generate a refresh tokens to be granted to applications.  The application (e.g. like a bank system or SAP) shall implement its own relevant user authority checks to this refresh token (which nonetheless will expire on a longer term basis, or be revoked by the user). 

And the refresh token is used to generate an access token. The access token is what's most commonly used to authenticate to different API endpoints. The access token commonly expires in a very short amount of time (less than 10 minutes)

It's a keen interest of mine to be able to interface different DID issuers/providers. The format and standard of DIDs I believe is meant to support that. 

Related to BRI-1 - here's a gist that can be used in the PRVD CLI to populate a refresh token to a local directory
https://gist.github.com/fleischr/6aecd5ace9a4d2f772c044d7d6046ad7

**Comment by sf316** [comment]
Work in progress. Link to the [doc](https://docs.google.com/document/d/1L5VUsyMy_0iJjh6HwuG3wl0IyiCEVFKp1ZS_rbJ0u1g/edit?usp=sharing).

**Comment by ognjenkurtic** [comment]
@sf316 this issue can be closed now?

**Comment by sf316** [comment]
> @sf316 this issue can be closed now?

I think so. But I can't close it from my side.
