### ISSUE TITLE
[SRI] - Merkelize payload as part of workstep execution

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#698]
## Overview

Based on the description from the SRI use-case doc, we need to merkelize the payload of the BpiTransaction (an invoice) that is triggering workstep 1 to be able to prepare it for circuit execution and subsequent storage. Scope of this story is to implement this merkelization only. storage will come later.

It should be implemented as a pure function of merkleTree.service.ts, taking the payload of the BpiTransaction as raw JSON and producing a merkle tree out of it. It has to produce deterministic results for the same input.

Example input from the SRI use-case doc:

```
payload:  “{ 
    "SupplierInvoiceID":"INV123",
    "Amount": 300,
    "IssueDate":"2023-06-15",
    "DueDate":"2023-07-15",
    "Status”:"NEW",
    Items: [
 	    {1, product1, 100, 1},
 	    {2, product2, 200, 1}
    ]
 }”,

```

Example code from the SRI use-case doc

```
import { ChildNodes, SparseMerkleTree } from "@zk-kit/sparse-merkle-tree"

const hash = (childNodes: ChildNodes) => sha256(childNodes.join("")).toString()
const tree = new SparseMerkleTree(hash)

tree.add("0", "31"); // BpiId:1
tree.add("1", "494e562d313233"); // SupplierInvoiceID:INV-123
tree.add("2", "0"); // BuyerInvoiceId:null
tree.add("3", "3330302e3030"); // Amount:300.00
tree.add("4", "323032332d30362d3135"); // IssueDate:2023-06-15
tree.add("5", "323032332d30372d3135"); // DueDate:2023-07-15
tree.add("6", "4e4557"); // Status:NEW

const anyTree = tree as any;
console.log(JSON.stringify(Array.from(anyTree.nodes)));
```
Also look into the implementation of addLeaves in the bpiMerkleTree.ts

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit)

### Questions

- How do we merkelize the items of the invoice?

### Tasks

- [x] Implement the function to merkelize the payload
- [x] Write tests
- [ ] Implement the merkelization of the payload as part of workstep execution

**Comment by ognjenkurtic** [comment]
Closed by mistake. We need to merkelize the payload of the transaction that is executed as part of the workstep for this issue to be closed. Storage of the merkelized payload will come as part of  #702

**Comment by ognjenkurtic** [comment]
@Kasshern do we need another issue for the comment above or is it ok to work under this one?

**Comment by Kasshern** [comment]
> @Kasshern do we need another issue for the comment above or is it ok to work under this one?

Ok to work under this one.
