### ISSUE TITLE
[SRI] Handle workstep execution failures

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#703]
## Overview

Based on the description from the SRI use-case doc, we need a mechanism to handle failures during workstep execution. If anything goes wrong ,we need to at least abort the transaction and inform relevant participants.

In the ExecuteVsmCycleCommandHandler, transaction is already set to Invalid in case validation fails and Aborted in case execution fails. Before returning, we should:

1. Log the result using our logger
2. Construct a BpiMessage of new type ERR, with a standardized error message payload and publish back on the channel of the initiator of the transaction. This will later be changed to publish additional only on the workgroup channel or also to the recipient of the transaction. 

Initiator message channel = tx.fromBpiSubjectAccount.ownerBpiSubject.publicKey

Look into best ways to execute these two steps while avoiding code duplication. Maybe NestJs event or Saga can help here?

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit)

### Questions

- What is the standardized error message payload we want to use? Keep it as simple as possible for now.

**Comment by ognjenkurtic** [comment]
@ognjenkurtic provide detailed description with acceptance criteria

**Comment by Therecanbeonlyone1969** [comment]
Closing after PR #726 merged.
