### ISSUE TITLE
[SRI] Generate and store content addressable hash after workstep execution

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#704]
## Overview

Based on the description from the SRI use-case doc, we want to generate content addressable hash during workstep execution that should be stored outside of the BPI and used to reference a specific version of the state. Scope is to agree on the generation and storage and implement it.

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit)

### Questions

- We need to agree on #698, #699, #700, #701, #702 before this one can be picked up.

### Tasks
- [x] Implement storage of the CAH (new state leaf value) on-chain after succesfull state storage
- [ ] Implement endpoint that performs verification that CAH is part of the state tree

**Comment by biscuitdey** [comment]
The following PRs may be re-utilised for this issue.
1. [Connect & store hash on blockchain](https://github.com/eea-oasis/baseline/pull/641)
2. [Retrieve content addressable hash from local storage](https://github.com/eea-oasis/baseline/pull/613)

**Comment by Ybittan** [comment]
Core Dev Call 8/21 - 

1) @Kasshern - Need to agree on what the content addressable hash is, and a solution assuming an outside party replicates the generation of this hash, should be able to verify that this is correct.  

2) @ognjenkurtic New Issue - Storing state change hashes on the blockchain is for immutability, need to include this on state execution to store this on chain. Needs a separate issue to be opened. Shree has code already for adding to testnet that can be reused. 

3) Stretch goal (beyond) - For this to be meaningful, a system in place to prove the state was updated only by the BPI, through signatures etc. Content addressable hash allows you to get to the information if you want more validity.

**Comment by Kasshern** [comment]
@biscuitdey @ognjenkurtic @Therecanbeonlyone1969 @Ybittan @sf316  per an async conversation with Ognjen: 
The content addressable hash should be the newly produced stateLeafValue.  The value can be used to retrieve the leaf index, which in turn, allows retrieval of the merkelized payload and witness used to create the leaf. 

Assuming this will be stored in the local DB, there should exist a route that when a correctly calculated content addressable hash is passed in said endpoint will execute a query that verifies the CAH is included within the state tree and the history tree. Resolution of CAH will present either confirmation or refutation.
