### ISSUE TITLE
SRI - Implement functions to connect & interact with CCSM

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#762]
## Overview

Use etherjs or similar library to connect and interact with onchain anchor hash contract.

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- List any assumptions that
- You are making in terms of timeframe,
- Output, or general context setting

### Acceptance

- List of what needs to be true
- to consider this done
- done done

## Tasks

- [ ] A list of tasks that need
- [ ] to be done to call this issue done

**Comment by ognjenkurtic** [comment]
Closing this one in favor of this one https://github.com/eea-oasis/baseline/issues/751 and the issues that will be opened based on it
