### ISSUE TITLE
SRI - Implement schema parser for translating tx payload into circom inputs 

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#776]
## Overview

Implement the parser based on the description in the [design document](https://docs.google.com/document/d/1AzyUK0OMATe0XRPaTbayRR3KmuaFLMAKybIytaVVBdY/edit). It should support all the cases  present there. 

Should be implemented as a standalone stateless service that accepts a schema object in JSON and produces an object representing  circom inputs ready for consumption.

Make sure to write unit tests for various schema use-cases (nested fields, various data types, default values, errors etc.)

### Reference

https://github.com/eea-oasis/baseline/issues/744
https://github.com/eea-oasis/baseline/issues/766

### Acceptance

- Parser implemented as a standalone service
- Supports all the cases present in the deisgn doc example
- 100% test coverage

## Tasks

- [x] Do it

**Comment by Ybittan** [comment]
ZK Circuits Input Transformer
